<?xml version = "1.0" standalone="yes"?>
<!DOCTYPE DOCUMENT [
    <!ELEMENT DOCUMENT (BOOK)*>
    <!ELEMENT BOOK (AUTHOR, PUBLISHER)>
    <!ELEMENT AUTHOR (FIRST_NAME, LAST_NAME)>
    <!ELEMENT FIRST_NAME (#PCDATA)>
    <!ELEMENT LAST_NAME (#PCDATA)>
    <!ELEMENT PUBLISHER (NAME,ISBN)>
    <!ELEMENT NAME (#PCDATA)>
    <!ELEMENT ISBN (#PCDATA)>
    <!ELEMENT PUB_DATE (MONTH,YEAR)>
    <!ELEMENT MONTH (#PCDATA)>
    <!ELEMENT YEAR (#PCDATA)>    
    <!ELEMENT LoC_NUM (#PCDATA)>


]>

<DOCUMENT>
    <BOOK>
        <AUTHOR>
            <FIRST_NAME></FIRSTNAME>
            <LAST_NAME></LAST_NAME>
        </AUTHOR>
        <PUBLISHER>
            <NAME></NAME>
            <ISBN></ISBN>
        </PUBLISHER>
        <PUB_DATE>
            <MONTH></MONTH>
            <YEAR></YEAR>
        </PUB_DATE>
        <LoC_NUM></LoC_NUM>
    </BOOK>
</DOCUMENT>

first, last for as many co-authors as there are), publisher (including publisher name, and ISBN number for the book
