=== jackienobbe/CS315/a6/catalog.dtd
<!ELEMENT CATALOG (BOOK*)>
    <!ELEMENT BOOK (TITLE, AUTHOR+, PUBLISHER*, PUB_DATE, LoC_NUM)>
    <!ELEMENT TITLE (#PCDATA)>
    <!ELEMENT AUTHOR EMPTY>
        <!ATTLIST AUTHOR first_name CDATA #IMPLIED>
        <!ATTLIST AUTHOR last_name CDATA #REQUIRED>
    <!ELEMENT PUBLISHER (NAME,ISBN)>
    <!ELEMENT NAME (#PCDATA)>
    <!ELEMENT ISBN (#PCDATA)>
    <!ELEMENT PUB_DATE EMPTY>
        <!ATTLIST PUB_DATE month ( Jan | Feb | Mar | Apr | May | Jun | Jul | Aug | Sept | Oct | Nov | Dec ) #IMPLIED>
        <!ATTLIST PUB_DATE year CDATA #REQUIRED>
    <!ELEMENT LoC_NUM (#PCDATA)>

=== jackienobbe/CS315/a6/catalog.xml
<?xml version = "1.0"?>
<!DOCTYPE CATALOG SYSTEM "http://ice.truman.edu/~jen1141/a6/catalog.dtd">

<CATALOG>
    <BOOK>
        <TITLE></TITLE>
        <AUTHOR first_name="" last_name=""></AUTHOR>
        <PUBLISHER>
            <NAME></NAME>
            <ISBN></ISBN>
        </PUBLISHER>
        <PUB_DATE month="" year=""></PUB_DATE>
        <LoC_NUM></LoC_NUM>
    </BOOK>
</CATALOG>
